### ISSUE TITLE
✨ 유저 엔티티 추가

### ISSUE THREAD

**Issue by jjikky** [spring-bud/mate-be#4]
### ✨ 진행할 작업 설명

유저 엔티티 관련 도메인 설계 및 구현 작업을 진행합니다. 사용자 정보를 관리하는 엔티티 클래스, 상태 관리 열거형, 닉네임 생성 정책, 레포지토리 인터페이스를 정의하고, 관련 도메인 로직과 유틸리티 메서드를 추가합니다.

---

### 🚀 TODO

- [x] 유저 엔티티(User) 정의 및 필드 추가
- [x] 유저 상태 열거형(UserStatus) 정의
- [x] 닉네임 생성 정책(DefaultNicknamePolicy) 구현
- [x] 사용자 레포지토리(UserRepository) 인터페이스 정의
- [x] 유저 정보 수정 및 탈퇴 로직 추가
- [x] 유저 관련 비즈니스 로직 테스트 코드 작성

---
