### ISSUE TITLE
✨ API 응답 및 공통 예외 처리 시스템 추가

### ISSUE THREAD

**Issue by jjikky** [spring-bud/mate-be#5]
### ✨ 진행할 작업 설명

```markdown
API 응답 및 공통 예외 처리 시스템 추가
```

### 🚀 TODO

- [x] 공통 API 응답 구조를 위한 `ApiResponse` 추가
- [x] 기본 예외 클래스 및 인터페이스 정의
- [x] 글로벌 예외 핸들러 추가
- [x] 커스텀 예외 및 예외 응답 DTO 정의

### 🐋 연관된 이슈

- closed
- resolved
